import type { Metadata } from "next";
import "./globals.css";
import ThemeContextProvider from "./contexts/ThemeContext";
import Navbar from "./components/modules/Navbar/Navbar";
import Link from "next/link";
import { SidebarDemo } from "./components/modules/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en">
      <body className="font-poppins text-[16px] dark:text-neutral-200">
        <ThemeContextProvider>
          <section className="taskmanager-content__section">
            <Navbar />
            {children}
          </section>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
