import type { Metadata } from "next";
import "./globals.css";
import ThemeContextProvider from "./contexts/ThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
